package com.example.epam_internship_android_molodchenko.models

import com.google.gson.annotations.SerializedName

data class ModelMealDetails (
    @SerializedName("idMeal")
    val idMeal: String,
    @SerializedName("strMeal")
    @SerializedName("strDrinkAlternate")
    @SerializedName("strCategory")
    @SerializedName("strArea")
    @SerializedName("strInstructions")
    @SerializedName("strMealThumb")
    @SerializedName("strTags")
    @SerializedName("strYoutube")
    @SerializedName("strIngredient1")
    @SerializedName("strIngredient2")
    @SerializedName("strIngredient3")
    @SerializedName("strIngredient4")
    @SerializedName("strIngredient5")
    @SerializedName("strIngredient6")
    @SerializedName("strIngredient7")
    @SerializedName("strIngredient8")
    @SerializedName("strIngredient9")
    @SerializedName("strIngredient10")
    @SerializedName("strIngredient11")
    @SerializedName("strIngredient12")
    @SerializedName("strIngredient13")
    @SerializedName("strIngredient14")
    @SerializedName("strIngredient15")
    @SerializedName("strIngredient16")
    @SerializedName("strIngredient17")
    @SerializedName("strIngredient18")
    @SerializedName("strIngredient19")
    @SerializedName("strIngredient20")
    @SerializedName("strMeasure1")
    @SerializedName("strMeasure2")
    @SerializedName("strMeasure3")
    @SerializedName("strMeasure4")
    @SerializedName("strMeasure5")
    @SerializedName("strMeasure6")
    @SerializedName("strMeasure7")
    @SerializedName("strMeasure8")
    @SerializedName("strMeasure9")
    @SerializedName("strMeasure10")
    @SerializedName("strMeasure11")
    @SerializedName("strMeasure12")
    @SerializedName("strMeasure13")
    @SerializedName("strMeasure14")
    @SerializedName("strMeasure15")
    @SerializedName("strMeasure16")
    @SerializedName("strMeasure17")
    @SerializedName("strMeasure18")
    @SerializedName("strMeasure19")
    @SerializedName("strMeasure20")
    @SerializedName("strSource")
    @SerializedName("strImageSource")
    @SerializedName("strCreativeCommonsConfirmed")
    @SerializedName("dateModified")
        )